### ISSUE TITLE
failed to train when the dataset only has one class

### ISSUE THREAD

**Issue by wangzhenhua2015** [andreaazzini/retinanet.pytorch#3]
Some times "nan" occurred when printing average loss.

Train Epoch: 1
loc_loss: 0.928 | cls_loss: 3254.533 | train_loss: 3255.461 | avg_loss: 3255.461
loc_loss: 0.537 | cls_loss: 4028.960 | train_loss: 4029.497 | avg_loss: 3642.479
loc_loss: 0.552 | cls_loss: 7911.482 | train_loss: 7912.035 | avg_loss: 5065.664
loc_loss: 0.076 | cls_loss: 3852.595 | train_loss: 3852.671 | avg_loss: 4762.416
loc_loss: 0.122 | cls_loss: 3724.298 | train_loss: 3724.420 | avg_loss: 4554.817
loc_loss: 0.029 | cls_loss: 7151.779 | train_loss: 7151.808 | avg_loss: 4987.649
loc_loss: 0.066 | cls_loss: 1705.866 | train_loss: 1705.932 | avg_loss: 4518.832
loc_loss: 0.092 | cls_loss: 6472.781 | train_loss: 6472.873 | avg_loss: 4763.087
loc_loss: 0.092 | cls_loss: 3052.897 | train_loss: 3052.989 | avg_loss: 4573.076
loc_loss: nan | cls_loss: 6.013 | train_loss: nan | avg_loss: nan
loc_loss: 0.088 | cls_loss: 5181.375 | train_loss: 5181.463 | avg_loss: nan
loc_loss: 0.116 | cls_loss: 16.118 | train_loss: 16.234 | avg_loss: nan
loc_loss: 0.091 | cls_loss: 16.118 | train_loss: 16.209 | avg_loss: nan
loc_loss: 0.051 | cls_loss: 16.118 | train_loss: 16.169 | avg_loss: nan
loc_loss: 0.113 | cls_loss: 16.118 | train_loss: 16.231 | avg_loss: nan
loc_loss: 0.072 | cls_loss: 16.118 | train_loss: 16.190 | avg_loss: nan

**Comment by wangzhenhua2015** [comment]
The loss is zero. When num_class is one and model is tuned from resnet50:
"
loc_loss: 0.000 | cls_loss: 0.000 | Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train(epoch)
  File "train.py", line 83, in train
    loss.backward()
  File "/export/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/export/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/export/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/export/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/thnn/auto.py", line 54, in backward
    return ((backward_cls.apply(input, target, grad_output, ctx.additional_args, ctx._backend),) +
  File "/export/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/thnn/auto.py", line 65, in backward_cls_forward
    grad_output_expanded = grad_output.view(*repeat(1, grad_input.dim()))
TypeError: view received an invalid combination of arguments - got (), but expected one of:
 * (int ... size)
 * (torch.Size size)
"

**Comment by wangzhenhua2015** [comment]
When I upgraded from pytorch version 0.2 to 0.3  the issue is gone
