### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Issuenate** [andreaazzini/retinanet.pytorch#4]
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    train(epoch)
  File "train.py", line 82, in train
    loss = criterion(loc_preds, loc_targets, cls_preds, cls_targets)
  File "/home/issue/.environments/env27/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/issue/Desktop/retinanet.pytorch/loss.py", line 54, in forward
    print('loc_loss: %.3f | cls_loss: %.3f' % (loc_loss.data[0]/num_pos, cls_loss.data[0]/num_pos), end=' | ')

![image](https://user-images.githubusercontent.com/11188507/42624443-ffc10054-85f7-11e8-9e68-061de49af7f2.png)

Seems like there are some values are 0 so it can't be divided.
BTW, i am using my own dataset in VOC2007 format.
There is only one class inside of the dataset, i'm not sure if that works.
Do anyone know how to solve this problem? Thanks for helping!

**Comment by Issuenate** [comment]
Because the object in my dataset is smaller so sometimes it can't match any num_pos with target_box i guess?
After i change the scale of the image and the anchor box size and works.
